#!/usr/bin/python
import Action
import getopt
import sys
import os

def usage(mode='default'):
	executable_name = os.path.basename(sys.argv[0])

	usage_message = {
		'build': ' <directory>',
		'dependency': '(dep) [to|from] <document|package|requirement>',
		'new': ' [glossary|package|repository|requirement(req)|stakeholder] <name>',
		'report': ' <name>',
	}

	if mode == 'default':
		modes = ''
		for key, message in usage_message.items():
			modes = '%s|%s' % (key, modes)

		modes = modes.lstrip('|')
		modes = modes.rstrip('|')
		print 'Usage: %s [%s] <actions>' % (executable_name, modes)
	else:
		print 'Usage: %s %s%s' % (executable_name, mode, usage_message[mode])

	sys.exit(1)

def new_mode():
	if len(sys.argv) == 4:
		actions = ['glossary', 'package', 'repository', 'requirement', 'stakeholder']
		valid_action = False
		action = sys.argv[2]

		if action == 'req':
			action = 'requirement'

		for valid_action in actions:
			if action == valid_action:
				valid_action = True

		if valid_action:
			Action.new_item(action, sys.argv[3])
		else:
			print 'Error: Action "%s" not recognized' % action 
			usage('new')
	else:
		print 'Error: Too few or too many arguments'
		usage('new')

def dependency_mode():
	valid_arguments = False

	if len(sys.argv) == 4:
		direction = sys.argv[2]
		item = sys.argv[3]

		if direction == 'to' or direction == 'from':
			valid_arguments = True
		else:
			print 'Error: Unknown dependency direction "%s", must be either "to" or "from"' % direction
	else:
		print 'Error: Too few or too many arguments'

	if valid_arguments:
		Action.list_dependency(direction, item)
	else:
		usage('dependency')

def build_mode():
	if len(sys.argv) == 3:
		Action.build_artifacts(sys.argv[2])
	else:
		print 'Error: Too few or too many arguments'
		usage('build')

def report_mode():
	if len(sys.argv) == 3:
		Action.run_report(sys.argv[2])
	else:
		print 'Error: Too few or too many arguments'
		usage('report')

try:
	mode = sys.argv[1]
except Exception:
	usage()

options, remainder = getopt.getopt(sys.argv[2:], 'o:v', ['output=', 'verbose', 'version=', ])

if mode == "dependency" or mode == "dep":
	dependency_mode()
elif mode == "new":
	new_mode()
elif mode == "build":
	build_mode()
elif mode == "report":
	report_mode()
else:
	if mode != '':
		print 'Error: Unknown mode "%s"' % mode
	usage()
